import { StateGraph, StateSchema, START, END, type GraphNode, type CompiledStateGraph } from "@langchain/langgraph"
import z from "zod";
import { mistralAIModel, cohereModel, geminiModel } from "./models.ai.js";

const state = new StateSchema({
    problem: z.string().default(""),
    solution_1: z.string().default(""),
    solution_2: z.string().default(""),
    judge: z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
    })
})


const solutionNode: GraphNode<typeof state> = async (state) => {

    const [mistralResponse, cohereResponse] = await Promise.all([
        mistralAIModel.invoke(state.problem),
        cohereModel.invoke(state.problem)
    ])

    return {
        solution_1: mistralResponse.text,
        solution_2: cohereResponse.text,
    }
}

const judgeNode: GraphNode<typeof state> = async (state) => {
    const { problem, solution_1, solution_2 } = state

    const prompt = `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores.

Problem: ${problem}
Solution 1: ${solution_1}
Solution 2: ${solution_2}

Respond with a JSON object in this exact format:
{
  "solution_1_score": number (0-10),
  "solution_2_score": number (0-10),
  "solution_1_reasoning": "string",
  "solution_2_reasoning": "string"
}`

    const judgeResponse = await geminiModel.invoke(prompt)

    // Parse the JSON response
    let parsed
    try {
        parsed = JSON.parse(judgeResponse.content)
    } catch (e) {
        // Fallback if not JSON
        parsed = {
            solution_1_score: 5,
            solution_2_score: 5,
            solution_1_reasoning: "Unable to parse judge response",
            solution_2_reasoning: "Unable to parse judge response"
        }
    }

    const {
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    } = parsed

    return {
        judge: {
            solution_1_score,
            solution_2_score,
            solution_1_reasoning,
            solution_2_reasoning
        }
    }

}

const graph = new StateGraph(state)
    .addNode("solution", solutionNode)
    .addNode("judge_node", judgeNode)
    .addEdge(START, "solution")
    .addEdge("solution", "judge_node")
    .addEdge("judge_node", END)
    .compile()

export default async function (problem: string) { 

    const result = await graph.invoke({
        problem: problem
    })

    return result

}